# Generated by Django 5.1 on 2024-09-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0002_category_product_productinventory_purchaseorder_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesOrder',
        ),
        migrations.DeleteModel(
            name='SalesOrderItems',
        ),
    ]
