# Generated by Django 5.1 on 2024-09-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0004_salesorder_salesorderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderitems',
            name='sales_order',
        ),
        migrations.RemoveField(
            model_name='salesorderitems',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='SalesOrder',
        ),
        migrations.DeleteModel(
            name='SalesOrderItems',
        ),
    ]
