# Generated by Django 5.1 on 2024-09-13 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0006_salesorder_salesorderitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductInventory',
        ),
    ]
