# Generated by Django 5.1.1 on 2024-09-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0009_alter_product_cat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cat_id',
            new_name='category_id',
        ),
    ]
